version: '3.8'
services:
  bot:
    image: 'python:3.12'
    restart: unless-stopped
    working_dir: /code
    ports:
      - '127.0.0.1:6901:6901'
    volumes:
      - '.\\bot:/code/bot'
      - '.\\requirements.txt:/code/requirements.txt'
    command: |
      sh -c "pip install --upgrade pip && pip install --no-cache-dir --upgrade -r requirements.txt && python bot/bot.py"
    depends_on:
      - db
    networks:
      - server
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - server
  fastapi:
    ports:
      - '127.0.0.1:4547:3537'
    image: 'python:3.12'
    restart: unless-stopped
    working_dir: /code
    volumes:
      - '.\\bot:/code/bot'
      - '.\\requirements.txt:/code/requirements.txt'
    command: |
      sh -c "pip install --upgrade pip && pip install --no-cache-dir --upgrade -r requirements.txt && uvicorn bot.control:app --host 0.0.0.0 --port 3537 --reload"
    depends_on:
      - bot
    networks:
      - server
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=pass12345
      - MYSQL_ROOT_PASSWORD=pass12345
      - MYSQL_DATABASE=lsc-bot-system-database
    networks:
      - server
  redis-stack:
    image: redis/redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - server
networks:
  server: null
