version: '3.8'

services:
  tickets:
    image: python:3.12-alpine
    restart: unless-stopped

    working_dir: /code
    volumes:
      - .\\app:/code/app
      - .\\main.py:/code/main.py
      - .\\requirements.txt:/code/requirements.txt

    command: >
       sh -c "pip install --upgrade pip &&
       pip install --no-cache-dir --upgrade -r requirements.txt &&
       python app/bots/bot_tickets.py"

  music:
    image: python:3.12-alpine
    restart: unless-stopped

    working_dir: /code
    volumes:
      - .\\app:/code/app
      - .\\main.py:/code/main.py
      - .\\requirements.txt:/code/requirements.txt

    command: >
       sh -c "pip install --upgrade pip &&
       pip install --no-cache-dir --upgrade -r requirements.txt &&
       python app/bots/bot_music.py"

  moderator:
    image: python:3.12-alpine
    restart: unless-stopped

    working_dir: /code
    volumes:
      - .\\app:/code/app
      - .\\main.py:/code/main.py
      - .\\requirements.txt:/code/requirements.txt

    command: >
       sh -c "pip install --upgrade pip &&
       pip install --no-cache-dir --upgrade -r requirements.txt &&
       python app/bots/bot_moderator.py"

# docker compose down
# docker compose up -d